### PR TITLE
Fixing missing class

### PR DESCRIPTION
**Pull request by TomasVotruba**
Working on https://github.com/symplify/symplify/issues/1549

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Fixed :+1:

**Comment by enumag** [comment]
Can you tell me what the problem was? And why it wasn't affecting your usages of ECS Tester? If it was autoloading issue then why normal composer autoloading didn't work?

**Comment by TomasVotruba** [comment]
Autoloading issue. PHP CodeSniffer has own custom legacy way to load classes, so the file has to be included manually.

**Comment by TomasVotruba** [comment]
See https://github.com/symplify/symplify/pull/1812/files#diff-6a77d5a50fa025133e62e22812a2be97

**Comment by TomasVotruba** [comment]
In Symplify I have to load it manually in `tests/bootstrap.php`: https://github.com/symplify/symplify/blob/cff066d5b80410a7075a9ff1044d71fa89fde08f/tests/bootstrap.php#L8

**Comment by enumag** [comment]
I see. Thanks for both explaining and fixing the bug!

**Pull request closed without merging**
